### ISSUE TITLE
新的commit中存在BUG

### ISSUE THREAD

**Issue by Lwxiang** [Lwxiang/bombRoom#6]
访问了:`http://115.28.65.51:8080/index/%7BserverURL%7D/allot/`

这样的URL

之后的主页用`/`吧,把`/index/`去掉

**Comment by Lwxiang** [comment]
不清楚为什么`{serverURL}`没有被赋值

我把服务器更新了,你可以看一下

**Comment by ccloli** [comment]
Fixed, 昨天的 commit 忘记 push 了 orz
