### ISSUE TITLE
考虑使用 push 钩子部署

### ISSUE THREAD

**Issue by ccloli** [Lwxiang/bombRoom#8]
目前服务器上的代码不会随实时的代码改变，似乎是还没有做到自动同步。或许可以考虑在服务器端部署 push 钩子自动同步，或者考虑在 heroku 上配置环境并部署自动同步。

**Comment by Lwxiang** [comment]
目前部署用的是阿里云,已经添加了push钩子,或者发送任意POST请求至/restart/,服务器将会自动pull并更新,延迟大概等个几秒钟。
